name : Petch
  version : 1.0
  enabled : true
tags : 
  - devops
  - yml
  - config
  
#String
title: "DevOps Training"

#Number
retries: 3

#Boolean
debug: true

#list
servers:
  - server1
  - server2
  - server3

#Dictionary (Object)
database :
  host : "localhost"
  port : 3306